CREATE TABLE ST_TYPE (
    ST_COLCODE INT, 
    ST_COLDESC VARCHAR(200)
);

INSERT INTO ST_TYPE (ST_COLCODE, ST_COLDESC)
    SELECT DISTINCT ST_COLCODE, ST_COLDESC
    FROM collisions 
    ORDER BY ST_COLCODE ASC;

CREATE TABLE test2 AS 
    SELECT col.*, t.ST_COLCODE AS ST_TYPE_ID
    FROM collisions col
    JOIN ST_TYPE t ON col.ST_COLCODE = t.ST_COLCODE;

UPDATE test2 AS t2
    SET ST_TYPE_ID = t.ST_COLCODE
    FROM ST_TYPE AS t
    WHERE t2.ST_COLCODE = t.ST_COLCODE
    AND t2.ST_COLDESC = t.ST_COLDESC;

ALTER TABLE test2 DROP COLUMN ST_COLCODE;
ALTER TABLE test2 DROP COLUMN ST_COLDESC;
ALTER TABLE collisions RENAME TO oldcollisions;
ALTER TABLE test2 RENAME TO collisions;

   