CREATE TABLE IF NOT EXISTS ST_SEVERITY (
  SEVERITY_id INT PRIMARY KEY NOT NULL,
  ST_SEVERITY_CODE VARCHAR(50),
  ST_SEVERITY_DESC VARCHAR(255)
);

INSERT INTO ST_SEVERITY (SEVERITY_id, ST_SEVERITY_CODE, ST_SEVERITY_DESC)
SELECT
  (SELECT MAX(SEVERITY_id) + 1 FROM ST_SEVERITY),
  SEVERITYCODE,
  SEVERITYDESC
FROM oldcollisions;
