-- select and drop statements --
SELECT * FROM test
SELECT * FROM SDOT_type
SELECT * FROM test_copy
SELECT * FROM collisions

DROP TABLE SDOT_type
DROP TABLE test_copy


-- start of code --

CREATE TABLE SDOT_type (
    SDOT_COLCODE INT,
    SDOT_COLDESC VARCHAR(255)
);

INSERT INTO SDOT_type (SDOT_COLCODE, SDOT_COLDESC)
SELECT DISTINCT SDOT_COLCODE, SDOT_COLDESC
FROM test
ORDER BY SDOT_COLCODE ASC;

CREATE TABLE test_copy AS
SELECT te.*, t.SDOT_COLCODE AS SDOT_TYPE_ID
FROM test te
JOIN SDOT_type t ON te.SDOT_COLCODE = t.SDOT_COLCODE;

UPDATE test_copy AS tc
SET SDOT_TYPE_ID = t.SDOT_COLCODE
FROM SDOT_type AS t
WHERE tc.SDOT_COLCODE = t.SDOT_COLCODE
  AND tc.SDOT_COLDESC = t.SDOT_COLDESC;
  
ALTER TABLE test_copy DROP COLUMN SDOT_COLCODE;
ALTER TABLE test_copy DROP COLUMN SDOT_COLDESC;

SELECT COUNT(*) AS row_count
FROM (
SELECT test_copy.OBJECTID, SDOT_type.SDOT_COLCODE, SDOT_type.SDOT_COLDESC
FROM SDOT_type
INNER JOIN test_copy ON SDOT_type.SDOT_COLCODE = test_copy.SDOT_TYPE_ID
WHERE test_copy.SDOT_TYPE_ID = 11) AS subquery;

ALTER TABLE test_copy RENAME TO collisions;