-- Creating a temp_conditions table for the purpose of grouping based on (weather, roadcond, lightcond) to get unique combinations 

CREATE TABLE IF NOT EXISTS temp_conditions1 AS SELECT WEATHER, ROADCOND, LIGHTCOND FROM test GROUP BY WEATHER, ROADCOND, LIGHTCOND;



-- Creating temp_conditions to assign a unique ID number (condit_id) to each distinct combination of WEATHER, ROADCOND, LIGHTCOND
-- NOTE: There are 447 unique combinations of weather/road/light conditions

CREATE TABLE IF NOT EXISTS conditions('condit_id' INTEGER PRIMARY KEY NOT NULL, 'WEATHER' TEXT, 'ROADCOND' TEXT, 'LIGHTCOND' TEXT); 
INSERT INTO conditions(WEATHER, ROADCOND, LIGHTCOND) SELECT WEATHER, ROADCOND, LIGHTCOND FROM temp_conditions1;

DROP TABLE temp_conditions1; -- Not needed anymore 




-- Doing it this way since doing 'SELECT *' is forbidden (?)
-- Includes an extra column 'condit_id' to hold the condit_id taken from the temp_conditions table
CREATE TABLE IF NOT EXISTS 'test_2'(
'X' TEXT, 'Y' TEXT, 'OBJECTID' TEXT, 'INCKEY' TEXT,
 'COLDETKEY' TEXT, 'REPORTNO' TEXT, 'STATUS' TEXT, 'ADDRTYPE' TEXT,
 'INTKEY' TEXT, 'LOCATION' TEXT, 'EXCEPTRSNCODE' TEXT, 'EXCEPTRSNDESC' TEXT,
 'SEVERITYCODE' TEXT, 'SEVERITYDESC' TEXT, 'COLLISIONTYPE' TEXT, 'PERSONCOUNT' TEXT,
 'PEDCOUNT' TEXT, 'PEDCYLCOUNT' TEXT, 'VEHCOUNT' TEXT, 'INJURIES' TEXT,
 'SERIOUSINJURIES' TEXT, 'FATALITIES' TEXT, 'INCDATE' TEXT, 'INCDTTM' TEXT,
 'JUNCTIONTYPE' TEXT, 'SDOT_COLCODE' TEXT, 'SDOT_COLDESC' TEXT, 'INATTENTIONIND' TEXT,
 'UNDERINFL' TEXT, 'WEATHER' TEXT, 'ROADCOND' TEXT, 'LIGHTCOND' TEXT, 'condit_id' INT,
 'PEDROWNOTGRNT' TEXT, 'SDOTCOLNUM' TEXT, 'SPEEDING' TEXT, 'ST_COLCODE' TEXT,
 'ST_COLDESC' TEXT, 'SEGLANEKEY' TEXT, 'CROSSWALKKEY' TEXT, 'HITPARKEDCAR' TEXT,
 'SOURCE' TEXT, 'SOURCEDESC' TEXT, 'ADDBY' TEXT, 'ADDDTTM' TEXT,
 'MODBY' TEXT, 'MODDTTM' TEXT, 'ST_PARTCPNT_TYPE' TEXT, 'ST_PARTCPNT_TYPE_DESC' TEXT,
 'ST_AGE' TEXT, 'ST_CITED' TEXT, 'ST_VEH_TYPE_CD' TEXT, 'ST_VEH_TYPE_DESC' TEXT,
 'ST_INJRY_CLSS_DESC' TEXT, FOREIGN KEY(condit_id) REFERENCES conditions(condit_id));



-- Now filling test_2 with data from test and temp_conditions

INSERT INTO test_2(X, Y, OBJECTID, INCKEY,
COLDETKEY, REPORTNO, STATUS, ADDRTYPE,
INTKEY, LOCATION, EXCEPTRSNCODE, EXCEPTRSNDESC,
SEVERITYCODE, SEVERITYDESC, COLLISIONTYPE, PERSONCOUNT,
PEDCOUNT, PEDCYLCOUNT, VEHCOUNT, INJURIES,
SERIOUSINJURIES, FATALITIES, INCDATE, INCDTTM,
JUNCTIONTYPE, SDOT_COLCODE, SDOT_COLDESC, INATTENTIONIND,
UNDERINFL, WEATHER, ROADCOND, LIGHTCOND, condit_id,
PEDROWNOTGRNT, SDOTCOLNUM, SPEEDING, ST_COLCODE,
ST_COLDESC, SEGLANEKEY, CROSSWALKKEY, HITPARKEDCAR,
SOURCE, SOURCEDESC, ADDBY, ADDDTTM,
MODBY, MODDTTM, ST_PARTCPNT_TYPE, ST_PARTCPNT_TYPE_DESC,
ST_AGE, ST_CITED, ST_VEH_TYPE_CD, ST_VEH_TYPE_DESC,
ST_INJRY_CLSS_DESC)

SELECT X, Y, OBJECTID, INCKEY,
COLDETKEY, REPORTNO, STATUS, ADDRTYPE,
INTKEY, LOCATION, EXCEPTRSNCODE, EXCEPTRSNDESC,
SEVERITYCODE, SEVERITYDESC, COLLISIONTYPE, PERSONCOUNT,
PEDCOUNT, PEDCYLCOUNT, VEHCOUNT, INJURIES,
SERIOUSINJURIES, FATALITIES, INCDATE, INCDTTM,
JUNCTIONTYPE, SDOT_COLCODE, SDOT_COLDESC, INATTENTIONIND,
UNDERINFL, t.WEATHER, t.ROADCOND, t.LIGHTCOND, c.condit_id,
PEDROWNOTGRNT, SDOTCOLNUM, SPEEDING, ST_COLCODE,
ST_COLDESC, SEGLANEKEY, CROSSWALKKEY, HITPARKEDCAR,
SOURCE, SOURCEDESC, ADDBY, ADDDTTM,
MODBY, MODDTTM, ST_PARTCPNT_TYPE, ST_PARTCPNT_TYPE_DESC,
ST_AGE, ST_CITED, ST_VEH_TYPE_CD, ST_VEH_TYPE_DESC,
ST_INJRY_CLSS_DESC FROM test as t, conditions as c
WHERE (t.WEATHER = c.WEATHER AND t.ROADCOND = c.ROADCOND AND t.LIGHTCOND = c.LIGHTCOND);

-- Cleaning up test_2; since we have condit_id and the conditions table, remove the (WEATHER, ROADCOND, LIGHTCOND) columns from the main table
ALTER TABLE test_2 DROP COLUMN WEATHER;
ALTER TABLE test_2 DROP COLUMN ROADCOND;
ALTER TABLE test_2 DROP COLUMN LIGHTCOND;





